"""Catalogo dei connettori MCP remoti ospitati dai fornitori (OAuth 2.1).

Portato dai manifest MIT di hermes-agent (optional-mcps): solo voci http+oauth.
Collegare = external.create + discovery + DCR + flusso browser (mcp_oauth).
"""

HOSTED_CONNECTORS = [
    {
        "name": 'airtable',
        "description": 'Bases, tables, and records from your Airtable workspace.',
        "url": 'https://mcp.airtable.com/mcp',
        "keywords": ['airtable'],
    },
    {
        "name": 'algolia',
        "description": 'Algolia search: indices, analytics, and settings (read-only).',
        "url": 'https://mcp.algolia.com/mcp',
        "keywords": ['algolia'],
    },
    {
        "name": 'amplitude',
        "description": 'Amplitude analytics: charts, dashboards, experiments, flags.',
        "url": 'https://mcp.amplitude.com/mcp',
        "keywords": ['amplitude'],
    },
    {
        "name": 'asana',
        "description": 'Tasks, projects, and goals from your Asana workspace.',
        "url": 'https://mcp.asana.com/v2/mcp',
        "keywords": ['asana'],
    },
    {
        "name": 'atlassian',
        "description": "Jira issues and Confluence pages via Atlassian's hosted remote MCP.",
        "url": 'https://mcp.atlassian.com/v1/mcp/authv2',
        "keywords": ['jira', 'confluence', 'atlassian', 'bitbucket'],
    },
    {
        "name": 'attio',
        "description": 'CRM records, lists, and notes in Attio.',
        "url": 'https://mcp.attio.com/mcp',
        "keywords": ['attio', 'crm'],
    },
    {
        "name": 'betterstack',
        "description": 'Better Stack: logs, uptime monitors, incidents, and status pages.',
        "url": 'https://mcp.betterstack.com',
        "keywords": ['better stack', 'betterstack', 'uptime monitor'],
    },
    {
        "name": 'buildkite',
        "description": 'CI/CD pipelines, builds, and test results from Buildkite.',
        "url": 'https://mcp.buildkite.com/mcp',
        "keywords": ['buildkite', 'ci'],
    },
    {
        "name": 'calendly',
        "description": 'Scheduling links, events, and invitees from Calendly.',
        "url": 'https://mcp.calendly.com',
        "keywords": ['calendly', 'scheduling'],
    },
    {
        "name": 'canva',
        "description": 'Create, search, and manage Canva designs.',
        "url": 'https://mcp.canva.com/mcp',
        "keywords": ['canva', 'design'],
    },
    {
        "name": 'circleci',
        "description": 'CircleCI: diagnose build failures, read logs, rerun workflows.',
        "url": 'https://mcp.circleci.com/v1/mcp',
        "keywords": ['circleci'],
    },
    {
        "name": 'clickup',
        "description": 'Tasks, docs, and workspaces in ClickUp.',
        "url": 'https://mcp.clickup.com/mcp',
        "keywords": ['clickup', 'task'],
    },
    {
        "name": 'close',
        "description": 'Sales CRM: leads, opportunities, calls, and emails.',
        "url": 'https://mcp.close.com/mcp',
        "keywords": ['close crm'],
    },
    {
        "name": 'cloudflare',
        "description": 'Full Cloudflare API access via the official remote MCP.',
        "url": 'https://mcp.cloudflare.com/mcp?codemode=false',
        "keywords": [],
    },
    {
        "name": 'cloudinary',
        "description": 'Upload, search, and transform media assets in Cloudinary.',
        "url": 'https://asset-management.mcp.cloudinary.com/mcp',
        "keywords": ['cloudinary', 'media assets'],
    },
    {
        "name": 'comfy-cloud',
        "description": 'Generate images, video, audio, and 3D on Comfy Cloud.',
        "url": 'https://cloud.comfy.org/mcp',
        "keywords": [],
    },
    {
        "name": 'craft',
        "description": 'Craft: structured docs, tasks, and personal knowledge base.',
        "url": 'https://mcp.craft.do/my/mcp',
        "keywords": ['craft docs'],
    },
    {
        "name": 'datadog',
        "description": 'Logs, monitors, dashboards, and incidents from Datadog.',
        "url": 'https://mcp.datadoghq.com/api/unstable/mcp-server/mcp',
        "keywords": ['datadog', 'apm'],
    },
    {
        "name": 'dropbox',
        "description": 'Search, read, and manage files in Dropbox.',
        "url": 'https://mcp.dropbox.com/mcp',
        "keywords": ['dropbox'],
    },
    {
        "name": 'figma',
        "description": 'Official Figma remote MCP — design context, Code Connect, and write-to-canvas via https://mcp.figma.com/mcp (OAuth).',
        "url": 'https://mcp.figma.com/mcp',
        "keywords": ['figma', 'mockup', 'wireframe'],
    },
    {
        "name": 'fireflies',
        "description": 'Meeting transcripts, summaries, and action items.',
        "url": 'https://api.fireflies.ai/mcp',
        "keywords": ['fireflies', 'meeting notes', 'transcript'],
    },
    {
        "name": 'gamma',
        "description": 'Gamma: generate and edit AI presentations, docs, and sites.',
        "url": 'https://mcp.gamma.app/mcp',
        "keywords": ['gamma', 'presentation'],
    },
    {
        "name": 'gitlab',
        "description": 'GitLab: issues, merge requests, pipelines, and repo context.',
        "url": 'https://gitlab.com/api/v4/mcp',
        "keywords": ['gitlab', 'merge request'],
    },
    {
        "name": 'globalping',
        "description": 'Ping, traceroute, DNS, and HTTP tests from global probes.',
        "url": 'https://mcp.globalping.dev/mcp',
        "keywords": ['globalping', 'traceroute', 'ping'],
    },
    {
        "name": 'grafana',
        "description": 'Query metrics, logs, dashboards, alerts, and incidents from Grafana Cloud.',
        "url": 'https://mcp.grafana.com/mcp',
        "keywords": ['grafana', 'promql', 'logql', 'observability', 'dashboard'],
    },
    {
        "name": 'hugging_face',
        "description": 'Models, datasets, Spaces, and papers from the Hugging Face Hub.',
        "url": 'https://huggingface.co/mcp',
        "keywords": ['hugging face', 'huggingface'],
    },
    {
        "name": 'indeed',
        "description": 'Search jobs and listings on Indeed.',
        "url": 'https://mcp.indeed.com/claude/mcp',
        "keywords": ['indeed', 'job search'],
    },
    {
        "name": 'intercom',
        "description": 'Conversations, tickets, and customer data from Intercom.',
        "url": 'https://mcp.intercom.com/mcp',
        "keywords": ['intercom'],
    },
    {
        "name": 'klaviyo',
        "description": 'Klaviyo marketing: campaigns, flows, segments, and reporting.',
        "url": 'https://mcp.klaviyo.com/mcp?core-tools-only=true&disable-tools-with-user-generated-content=true',
        "keywords": ['klaviyo'],
    },
    {
        "name": 'linear',
        "description": 'Find, create, and update Linear issues, projects, and comments.',
        "url": 'https://mcp.linear.app/mcp',
        "keywords": ['linear'],
    },
    {
        "name": 'miro',
        "description": 'Read and edit Miro boards, diagrams, and frames.',
        "url": 'https://mcp.miro.com/',
        "keywords": ['miro', 'whiteboard'],
    },
    {
        "name": 'mixpanel',
        "description": 'Mixpanel analytics: events, funnels, retention, dashboards.',
        "url": 'https://mcp.mixpanel.com/mcp',
        "keywords": ['mixpanel'],
    },
    {
        "name": 'monday',
        "description": 'Boards, items, docs, and workflows in monday.com.',
        "url": 'https://mcp.monday.com/mcp',
        "keywords": ['monday.com', 'monday board'],
    },
    {
        "name": 'motherduck',
        "description": 'MotherDuck: query DuckDB cloud warehouses with SQL.',
        "url": 'https://api.motherduck.com/mcp',
        "keywords": ['motherduck', 'duckdb'],
    },
    {
        "name": 'n8n-official',
        "description": "Connect to your n8n instance's official MCP server with browser OAuth.",
        "url": '${N8N_MCP_SERVER_URL}',
        "keywords": [],
    },
    {
        "name": 'neon',
        "description": 'Neon serverless Postgres: projects, branches, and SQL.',
        "url": 'https://mcp.neon.tech/mcp',
        "keywords": ['neon', 'postgres'],
    },
    {
        "name": 'netlify',
        "description": "Sites, deploys, and env vars via Netlify's hosted MCP.",
        "url": 'https://netlify-mcp.netlify.app/mcp',
        "keywords": ['netlify'],
    },
    {
        "name": 'notion',
        "description": 'Pages and databases from your Notion workspace.',
        "url": 'https://mcp.notion.com/mcp',
        "keywords": ['notion'],
    },
    {
        "name": 'paypal',
        "description": "Payments, invoices, and subscriptions via PayPal's hosted MCP.",
        "url": 'https://mcp.paypal.com/sse',
        "keywords": ['paypal'],
    },
    {
        "name": 'plaid',
        "description": 'Plaid dashboard: integrations, Items, and usage debugging.',
        "url": 'https://api.dashboard.plaid.com/mcp/',
        "keywords": ['plaid'],
    },
    {
        "name": 'postman',
        "description": 'Postman workspaces, collections, environments, and APIs.',
        "url": 'https://mcp.postman.com/minimal',
        "keywords": ['postman', 'api collection'],
    },
    {
        "name": 'prisma-postgres',
        "description": 'Create and manage Prisma Postgres databases.',
        "url": 'https://mcp.prisma.io/mcp',
        "keywords": ['prisma'],
    },
    {
        "name": 'railway',
        "description": 'Railway: projects, services, deployments, and environments.',
        "url": 'https://mcp.railway.com',
        "keywords": ['railway', 'railway deploy'],
    },
    {
        "name": 'robinhood',
        "description": 'Robinhood agentic trading: portfolio, balances, and orders.',
        "url": 'https://agent.robinhood.com/mcp/trading',
        "keywords": ['robinhood', 'stock trade'],
    },
    {
        "name": 'semgrep',
        "description": 'Scan code for security vulnerabilities with Semgrep.',
        "url": 'https://mcp.semgrep.ai/mcp',
        "keywords": ['semgrep', 'static analysis'],
    },
    {
        "name": 'sentry',
        "description": 'Issues, stack traces, and error context from Sentry.',
        "url": 'https://mcp.sentry.dev/mcp',
        "keywords": ['sentry', 'stack trace', 'crash report'],
    },
    {
        "name": 'square',
        "description": "Catalog, orders, and payments via Square's hosted MCP.",
        "url": 'https://mcp.squareup.com/sse',
        "keywords": ['squareup'],
    },
    {
        "name": 'strava',
        "description": 'Strava: activities, fitness trends, training load (read-only).',
        "url": 'https://mcp.strava.com/mcp',
        "keywords": ['strava', 'running', 'cycling'],
    },
    {
        "name": 'stripe',
        "description": "Payments, customers, and invoices via Stripe's hosted MCP.",
        "url": 'https://mcp.stripe.com',
        "keywords": ['stripe'],
    },
    {
        "name": 'supabase',
        "description": 'Database, auth, and storage from your Supabase projects.',
        "url": 'https://mcp.supabase.com/mcp',
        "keywords": ['supabase'],
    },
    {
        "name": 'todoist',
        "description": 'Manage Todoist tasks and projects.',
        "url": 'https://ai.todoist.net/mcp',
        "keywords": ['todoist', 'todo'],
    },
    {
        "name": 'twelve-data',
        "description": 'Stocks, forex, and crypto market data from Twelve Data.',
        "url": 'https://mcp.twelvedata.com/mcp',
        "keywords": ['twelve data', 'stock price'],
    },
    {
        "name": 'vercel',
        "description": "Deployments, logs, and projects via Vercel's hosted MCP.",
        "url": 'https://mcp.vercel.com',
        "keywords": ['vercel'],
    },
    {
        "name": 'webflow',
        "description": "Sites, CMS collections, and pages via Webflow's hosted MCP.",
        "url": 'https://mcp.webflow.com/mcp',
        "keywords": ['webflow'],
    },
    {
        "name": 'wordpress-com',
        "description": 'WordPress.com: posts, pages, drafts, stats, and comments.',
        "url": 'https://public-api.wordpress.com/wpcom/v2/mcp/v1',
        "keywords": ['wordpress'],
    },
]
