"""Contracts, schemas and presets for Mixture of Agents (MoA) orchestration (H24).

at c9dca726514b709cf6e677d236a79fc8d0627f37 (MIT).
Homun provides native Mixture of Agents orchestration where reference models advise
in parallel without tool schemas, and an acting aggregator executes tools and emits
grounded responses, with configurable fanout cadence, privacy filters, and truthful
aggregate token/cost accounting.
"""
from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Literal, Optional, Tuple, Union

from pydantic import BaseModel, Field

# Supported cadences
CADENCE_USER_TURN = "user_turn"
CADENCE_PER_ITERATION = "per_iteration"
CADENCE_EVERY_N = "every_n"

# Privacy filter modes
PRIVACY_NONE = "none"
PRIVACY_DISPLAY = "display"
PRIVACY_FULL = "full"


class MoAReferenceModel(BaseModel):
    """Specification for an advisory reference model in MoA."""
    provider: str = Field(description="Provider identifier (e.g., openai_compatible, ollama, anthropic)")
    model: str = Field(description="Model identifier")
    temperature: Optional[float] = Field(default=None, description="Optional sampling temperature")
    label: Optional[str] = Field(default=None, description="Display label for this reference model")

    @property
    def display_label(self) -> str:
        return self.label or f"{self.provider}:{self.model}"


class MoAAggregator(BaseModel):
    """Specification for the acting aggregator model in MoA."""
    provider: str = Field(description="Provider identifier")
    model: str = Field(description="Model identifier")
    temperature: Optional[float] = Field(default=None, description="Optional sampling temperature")
    label: Optional[str] = Field(default=None, description="Display label for the aggregator")

    @property
    def display_label(self) -> str:
        return self.label or f"{self.provider}:{self.model}"


class MoAPreset(BaseModel):
    """Configuration for a named MoA preset."""
    name: str = Field(description="Preset name, e.g. 'default', 'deep_review'")
    reference_models: List[MoAReferenceModel] = Field(
        default_factory=list,
        description="List of advisory models that provide perspectives without tools",
    )
    aggregator: MoAAggregator = Field(
        description="The acting model that synthesizes advice and executes tools",
    )
    fanout: str = Field(
        default=CADENCE_USER_TURN,
        description="Advisor cadence: 'user_turn', 'per_iteration', or 'every_n:N'",
    )
    privacy_filter: str = Field(
        default=PRIVACY_NONE,
        description="Privacy filter mode: 'none', 'display', or 'full'",
    )
    enabled: bool = Field(default=True, description="Whether this preset is active")


@dataclass
class MoAAdvisorOutput:
    """Output generated by one advisory reference model."""
    label: str
    provider: str
    model: str
    content: str
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    estimated_cost: Optional[float] = None
    currency: Optional[str] = "USD"
    temperature: Optional[float] = None
    duration_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def parse_fanout_cadence(val: Union[str, Dict[str, Any], None]) -> Tuple[str, int]:
    """Parse and normalize fanout cadence into (mode, n).

    Supports:
    - 'user_turn' -> ('user_turn', 1)
    - 'per_iteration' -> ('per_iteration', 1)
    - 'every_n:3' -> ('every_n', 3)
    - {'mode': 'every_n', 'n': 3} -> ('every_n', 3)
    """
    if not val:
        return (CADENCE_USER_TURN, 1)

    if isinstance(val, dict):
        mode = str(val.get("mode") or "").strip().lower()
        if mode == CADENCE_EVERY_N:
            try:
                n = max(2, int(val.get("n", 3)))
                return (CADENCE_EVERY_N, n)
            except (ValueError, TypeError):
                return (CADENCE_EVERY_N, 3)
        if mode in (CADENCE_USER_TURN, CADENCE_PER_ITERATION):
            return (mode, 1)
        return (CADENCE_USER_TURN, 1)

    s = str(val).strip().lower()
    if s == CADENCE_PER_ITERATION:
        return (CADENCE_PER_ITERATION, 1)
    if s == CADENCE_USER_TURN:
        return (CADENCE_USER_TURN, 1)

    m = re.match(r"^every_n:(\d+)$", s)
    if m:
        try:
            n = max(2, int(m.group(1)))
            return (CADENCE_EVERY_N, n)
        except ValueError:
            return (CADENCE_EVERY_N, 3)

    return (CADENCE_USER_TURN, 1)


def should_run_advisors(
    cadence_mode: str,
    every_n: int,
    iteration_index: int,
    has_cached_guidance: bool = False,
) -> bool:
    """Determine whether reference advisors should execute on this step.

    - CADENCE_USER_TURN: only on iteration 0 (first step of turn).
    - CADENCE_PER_ITERATION: on every iteration (iteration >= 0).
    - CADENCE_EVERY_N: on iteration 0, and then every every_n-th iteration (e.g. 0, 3, 6).
    """
    if cadence_mode == CADENCE_PER_ITERATION:
        return True
    if cadence_mode == CADENCE_EVERY_N:
        if iteration_index == 0:
            return True
        return (iteration_index % every_n == 0)
    # Default is CADENCE_USER_TURN
    return iteration_index == 0


def format_reference_guidance(
    advisors: List[MoAAdvisorOutput],
    privacy_filter: str = PRIVACY_NONE,
) -> str:
    """Format advisor outputs into a reference guidance block for the aggregator."""
    if not advisors:
        return ""

    from homun.application.moa_filter import apply_privacy_filter

    sections: List[str] = []
    for adv in advisors:
        body = adv.content
        if privacy_filter == PRIVACY_FULL:
            body = apply_privacy_filter(body, mode=PRIVACY_FULL)
        sections.append(
            f"### Advisory perspective from {adv.label} ({adv.provider}:{adv.model}):\n{body.strip()}"
        )

    joined = "\n\n".join(sections)
    return f"<reference_responses>\n{joined}\n</reference_responses>"
