# GENERATED by scripts/build_fonts.py — do not edit by hand.
# family -> {weight: woff2 filename (relative to fonts/)}
FONTS = {
    "Inter": {
        400: "inter-400.woff2",
        700: "inter-700.woff2"
    },
    "Roboto": {
        400: "roboto-400.woff2",
        700: "roboto-700.woff2"
    },
    "Open Sans": {
        400: "open-sans-400.woff2",
        700: "open-sans-700.woff2"
    },
    "Lato": {
        400: "lato-400.woff2",
        700: "lato-700.woff2"
    },
    "Work Sans": {
        400: "work-sans-400.woff2",
        700: "work-sans-700.woff2"
    },
    "Montserrat": {
        400: "montserrat-400.woff2",
        700: "montserrat-700.woff2"
    },
    "Poppins": {
        400: "poppins-400.woff2",
        700: "poppins-700.woff2"
    },
    "Source Serif 4": {
        400: "source-serif-4-400.woff2",
        700: "source-serif-4-700.woff2"
    },
    "Lora": {
        400: "lora-400.woff2",
        700: "lora-700.woff2"
    },
    "Merriweather": {
        400: "merriweather-400.woff2",
        700: "merriweather-700.woff2"
    },
    "Playfair Display": {
        400: "playfair-display-400.woff2",
        700: "playfair-display-700.woff2"
    },
    "JetBrains Mono": {
        400: "jetbrains-mono-400.woff2",
        700: "jetbrains-mono-700.woff2"
    }
}
