//! Process Skill — the addon abstraction (ADR 0011).
//!
//! A *process skill* is a vetted, configurable automation: a **trigger**, ordered
//! **steps** (deterministic where possible, agent-driven where data/UI varies),
//! typed **config/data**, **approval** points, and an optional **channel binding**.
//! All verticality lives here, NOT in the agnostic core.
//!
//! The **customization contract** lets a user adapt a vetted skill to their work by
//! prompt, *safely*: every config field is marked OPEN (editable) or LOCKED
//! (invariant — fiscal/legal/data-contract). A user's customization is a data
//! **overlay** validated against the contract — changes to locked fields are
//! rejected — so one vetted skill serves many users without forks, and central
//! upgrades re-apply the overlay cleanly.
//!
//! This crate is the *data model + contract validation*, extracted from the
//! canonical invoicing case (see `invoicing_example`). Execution wiring, a store,
//! and generation live in higher layers.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

/// How a process skill starts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "trigger", rename_all = "snake_case")]
pub enum Trigger {
    /// Run on demand (user asks).
    Manual,
    /// An inbound message on a channel (e.g. "whatsapp").
    Channel { source: String },
    /// A recurrence rule (reuses the runtime's recurrence grammar) + timezone.
    Schedule {
        recurrence: String,
        #[serde(default)]
        timezone: Option<String>,
    },
    /// An observed event of a given kind.
    Event { kind: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StepKind {
    /// Deterministic, config-driven action (compute totals, fill a template).
    Deterministic,
    /// Agent/LLM/tool task with a goal — used where the data or UI varies.
    Agent,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Step {
    pub id: String,
    pub kind: StepKind,
    pub description: String,
    /// Locked steps are invariants (they make the skill correct) — customization
    /// can neither remove nor reorder them. Open steps may be toggled by an overlay.
    #[serde(default)]
    pub locked: bool,
    /// Requires explicit user approval before it runs.
    #[serde(default)]
    pub requires_approval: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldType {
    Text,
    Number,
    Bool,
    Money,
    Date,
    List,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConfigField {
    pub key: String,
    pub label: String,
    #[serde(rename = "type")]
    pub field_type: FieldType,
    pub value: Value,
    /// The customization contract, per field: `true` = OPEN (adaptable by overlay),
    /// `false` = LOCKED (invariant — e.g. fiscal/legal fields, the data contract).
    pub editable: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Origin {
    /// Installed from the marketplace (vetted by us/partners).
    Installed,
    /// Authored by the user.
    Authored,
    /// Generated by the system from conversation/observation (apprentice loop).
    Generated,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProcessSkill {
    pub id: String,
    pub name: String,
    pub version: u32,
    pub description: String,
    pub origin: Origin,
    pub trigger: Trigger,
    pub steps: Vec<Step>,
    pub config: Vec<ConfigField>,
    /// Optional default channel for I/O (e.g. deliver the draft via WhatsApp).
    #[serde(default)]
    pub channel_binding: Option<String>,
    /// Whether users may add their own optional custom fields via an overlay.
    #[serde(default)]
    pub allows_custom_fields: bool,
}

impl ProcessSkill {
    pub fn field(&self, key: &str) -> Option<&ConfigField> {
        self.config.iter().find(|field| field.key == key)
    }
}

/// A user's customization: a data patch over a vetted skill, authored via prompt.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Overlay {
    /// `key → new value`, applied ONLY to OPEN (editable) config fields.
    #[serde(default)]
    pub changes: BTreeMap<String, Value>,
    /// Extra user fields, allowed only when the skill `allows_custom_fields`.
    #[serde(default)]
    pub added_fields: Vec<ConfigField>,
    /// Overlay version, for upgrade-safe re-application across skill upgrades.
    #[serde(default)]
    pub version: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Violation {
    pub key: String,
    pub reason: String,
}

/// Validates an overlay against the skill's customization contract. Returns the
/// list of violations (empty = valid).
///
/// Rules:
/// - a changed key must EXIST and be `editable` (open) — locked/invariant or
///   unknown keys are rejected with a clear reason;
/// - added fields are allowed only when the skill `allows_custom_fields`, and may
///   not collide with an existing key.
pub fn validate_overlay(skill: &ProcessSkill, overlay: &Overlay) -> Vec<Violation> {
    let mut violations = Vec::new();
    for key in overlay.changes.keys() {
        match skill.field(key) {
            None => violations.push(Violation {
                key: key.clone(),
                reason: "field does not exist in the component".to_string(),
            }),
            Some(field) if !field.editable => violations.push(Violation {
                key: key.clone(),
                reason: "LOCKED field (invariant): not customizable".to_string(),
            }),
            Some(_) => {}
        }
    }
    for added in &overlay.added_fields {
        if !skill.allows_custom_fields {
            violations.push(Violation {
                key: added.key.clone(),
                reason: "this component does not allow custom fields".to_string(),
            });
        } else if skill.field(&added.key).is_some() {
            violations.push(Violation {
                key: added.key.clone(),
                reason: "a field with this key already exists".to_string(),
            });
        }
    }
    violations
}

/// Applies a VALID overlay, returning the effective (customized) skill. Validate
/// first with `validate_overlay`; this also skips invalid changes defensively, so
/// a locked field can never be mutated even if a stale overlay references it.
pub fn apply_overlay(skill: &ProcessSkill, overlay: &Overlay) -> ProcessSkill {
    let mut effective = skill.clone();
    for field in &mut effective.config {
        if field.editable {
            if let Some(new_value) = overlay.changes.get(&field.key) {
                field.value = new_value.clone();
            }
        }
    }
    if effective.allows_custom_fields {
        for added in &overlay.added_fields {
            if effective.field(&added.key).is_none() {
                effective.config.push(added.clone());
            }
        }
    }
    effective
}

/// The canonical ADR 0011 case: a vetted "invoicing" process skill. Fiscal/legal
/// fields (VAT rate, legal numbering) are LOCKED invariants; branding, labels and
/// defaults are OPEN — the bespoke surface a user adapts by prompt. Used to prove
/// the model expresses a real, regulated addon.
pub fn invoicing_example() -> ProcessSkill {
    ProcessSkill {
        id: "invoicing".to_string(),
        name: "Invoicing".to_string(),
        version: 1,
        description: "Generates a compliant invoice draft (SdI/VAT) from the data of a request."
            .to_string(),
        origin: Origin::Installed,
        trigger: Trigger::Channel {
            source: "whatsapp".to_string(),
        },
        steps: vec![
            Step {
                id: "collect".to_string(),
                kind: StepKind::Agent,
                description: "Collect customer, line items and amounts from the request"
                    .to_string(),
                locked: false,
                requires_approval: false,
            },
            Step {
                id: "compute_totals".to_string(),
                kind: StepKind::Deterministic,
                description: "Compute taxable amount, VAT and total".to_string(),
                locked: true,
                requires_approval: false,
            },
            Step {
                id: "assign_number".to_string(),
                kind: StepKind::Deterministic,
                description: "Sequential legal numbering".to_string(),
                locked: true,
                requires_approval: false,
            },
            Step {
                id: "render".to_string(),
                kind: StepKind::Deterministic,
                description: "Compose the document from the template".to_string(),
                locked: false,
                requires_approval: false,
            },
            Step {
                id: "deliver".to_string(),
                kind: StepKind::Agent,
                description: "Send the draft to the user for confirmation".to_string(),
                locked: false,
                requires_approval: true,
            },
        ],
        config: vec![
            ConfigField {
                key: "company_name".to_string(),
                label: "Company name".to_string(),
                field_type: FieldType::Text,
                value: Value::String(String::new()),
                editable: true,
            },
            ConfigField {
                key: "logo_path".to_string(),
                label: "Logo".to_string(),
                field_type: FieldType::Text,
                value: Value::String(String::new()),
                editable: true,
            },
            ConfigField {
                key: "invoice_title".to_string(),
                label: "Document title".to_string(),
                field_type: FieldType::Text,
                value: Value::String("Invoice".to_string()),
                editable: true,
            },
            ConfigField {
                key: "vat_rate".to_string(),
                label: "VAT rate (%)".to_string(),
                field_type: FieldType::Number,
                value: serde_json::json!(22),
                editable: false, // LOCKED: fiscal invariant
            },
            ConfigField {
                key: "numbering_scheme".to_string(),
                label: "Numbering scheme".to_string(),
                field_type: FieldType::Text,
                value: Value::String("YYYY/NNN".to_string()),
                editable: false, // LOCKED: legal invariant
            },
        ],
        channel_binding: Some("whatsapp".to_string()),
        allows_custom_fields: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn invoicing_skill_round_trips_through_json() {
        let skill = invoicing_example();
        let json = serde_json::to_string(&skill).unwrap();
        let back: ProcessSkill = serde_json::from_str(&json).unwrap();
        assert_eq!(skill, back);
    }

    #[test]
    fn overlay_on_open_field_is_valid_and_applies() {
        let skill = invoicing_example();
        let mut overlay = Overlay::default();
        overlay.changes.insert(
            "invoice_title".to_string(),
            Value::String("Ricevuta".to_string()),
        );

        assert!(validate_overlay(&skill, &overlay).is_empty());
        let effective = apply_overlay(&skill, &overlay);
        assert_eq!(
            effective.field("invoice_title").unwrap().value,
            Value::String("Ricevuta".to_string())
        );
    }

    #[test]
    fn overlay_on_locked_field_is_rejected_and_never_applied() {
        let skill = invoicing_example();
        let mut overlay = Overlay::default();
        overlay
            .changes
            .insert("vat_rate".to_string(), serde_json::json!(10));

        let violations = validate_overlay(&skill, &overlay);
        assert_eq!(violations.len(), 1);
        assert_eq!(violations[0].key, "vat_rate");

        // Defensive: apply must not mutate a locked invariant even if asked.
        let effective = apply_overlay(&skill, &overlay);
        assert_eq!(
            effective.field("vat_rate").unwrap().value,
            serde_json::json!(22)
        );
    }

    #[test]
    fn overlay_on_unknown_field_is_rejected() {
        let skill = invoicing_example();
        let mut overlay = Overlay::default();
        overlay
            .changes
            .insert("nope".to_string(), Value::Bool(true));
        let violations = validate_overlay(&skill, &overlay);
        assert_eq!(violations.len(), 1);
        assert_eq!(violations[0].key, "nope");
    }

    #[test]
    fn custom_field_allowed_when_skill_permits_else_collision_rejected() {
        let skill = invoicing_example();

        // New custom field → valid + applied.
        let overlay = Overlay {
            added_fields: vec![ConfigField {
                key: "payment_terms".to_string(),
                label: "Termini di pagamento".to_string(),
                field_type: FieldType::Text,
                value: Value::String("30 giorni".to_string()),
                editable: true,
            }],
            ..Overlay::default()
        };
        assert!(validate_overlay(&skill, &overlay).is_empty());
        let effective = apply_overlay(&skill, &overlay);
        assert!(effective.field("payment_terms").is_some());

        // Colliding key → rejected.
        let overlay_collision = Overlay {
            added_fields: vec![ConfigField {
                key: "invoice_title".to_string(),
                label: "Dup".to_string(),
                field_type: FieldType::Text,
                value: Value::String("x".to_string()),
                editable: true,
            }],
            ..Overlay::default()
        };
        assert_eq!(validate_overlay(&skill, &overlay_collision).len(), 1);
    }
}
