const REASONING_MARKER_RE = /‹‹REASONING››[\s\S]*?‹‹\/REASONING››/g;
const STRAY_REASONING_MARKER_RE = /‹{1,2}\/?REASONING››/g;
const THINK_RE = /<think(?:ing)?>([\s\S]*?)<\/think(?:ing)?>/gi;
const THINK_OPEN_RE = /<think(?:ing)?>[\s\S]*$/i;
const LEAKED_TOOLCALL_RE = /<tool_call\b[\s\S]*?(?:<\/tool_call>|$)/gi;
const STRUCTURED_MARKER_RE =
  /‹‹(?:COMPOSIO_(?:CONFIRM|DONE|RECONNECT)|MCP_CONFIRM|FS_AUTHORIZE|SANDBOX_ESCALATE|SANDBOX_READONLY|CONNECT_SUGGEST|VAULT_PROPOSE|VAULT_REVEAL|PAYMENT_APPROVAL|CHOICES|CLARIFY|AWAIT_USER|PLAN_PROPOSE|GOAL_PROPOSE|PLAN|ACT|ARTIFACT|DIFF)››[\s\S]*?‹‹\/(?:COMPOSIO_(?:CONFIRM|DONE|RECONNECT)|MCP_CONFIRM|FS_AUTHORIZE|SANDBOX_ESCALATE|SANDBOX_READONLY|CONNECT_SUGGEST|VAULT_PROPOSE|VAULT_REVEAL|PAYMENT_APPROVAL|CHOICES|CLARIFY|AWAIT_USER|PLAN_PROPOSE|GOAL_PROPOSE|PLAN|ACT|ARTIFACT|DIFF)››/g;
const UNCLOSED_STRUCTURED_MARKER_RE =
  /‹‹(?:REASONING|COMPOSIO_CONFIRM|COMPOSIO_DONE|COMPOSIO_RECONNECT|MCP_CONFIRM|FS_AUTHORIZE|SANDBOX_ESCALATE|SANDBOX_READONLY|CONNECT_SUGGEST|VAULT_PROPOSE|VAULT_REVEAL|PAYMENT_APPROVAL|CHOICES|CLARIFY|AWAIT_USER|PLAN_PROPOSE|GOAL_PROPOSE|PLAN|ACT|ARTIFACT|DIFF)››[\s\S]*$/;

export function visibleAssistantText(text = "") {
  return text
    .replace(REASONING_MARKER_RE, "")
    .replace(THINK_RE, "")
    .replace(THINK_OPEN_RE, "")
    .replace(LEAKED_TOOLCALL_RE, "")
    .replace(STRUCTURED_MARKER_RE, "")
    .replace(UNCLOSED_STRUCTURED_MARKER_RE, "")
    .replace(STRAY_REASONING_MARKER_RE, "")
    .trim();
}
