/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppPipelinesRouteImport } from './routes/app.pipelines'
import { Route as AppPluginsRouteImport } from './routes/app.plugins'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppChatConversationIdRouteImport } from './routes/app.chat.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelinesRoute = AppPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsRoute = AppPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/plugins': typeof AppPluginsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/create': typeof AppCreateRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/plugins': typeof AppPluginsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/plugins': typeof AppPluginsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/chat'
    | '/app/create'
    | '/app/pipelines'
    | '/app/plugins'
    | '/app/team'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/app/create'
    | '/app/pipelines'
    | '/app/plugins'
    | '/app/team'
    | '/app'
    | '/app/chat/$conversationId'
    | '/app/chat'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/chat'
    | '/app/create'
    | '/app/pipelines'
    | '/app/plugins'
    | '/app/team'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipelines': {
      id: '/app/pipelines'
      path: '/pipelines'
      fullPath: '/app/pipelines'
      preLoaderRoute: typeof AppPipelinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plugins': {
      id: '/app/plugins'
      path: '/plugins'
      fullPath: '/app/plugins'
      preLoaderRoute: typeof AppPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/app/chat/$conversationId': {
      id: '/app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppCreateRoute: typeof AppCreateRoute
  AppPipelinesRoute: typeof AppPipelinesRoute
  AppPluginsRoute: typeof AppPluginsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppCreateRoute: AppCreateRoute,
  AppPipelinesRoute: AppPipelinesRoute,
  AppPluginsRoute: AppPluginsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
